### ISSUE TITLE
Implement frontend

### ISSUE THREAD

**Issue by kevinstadler** [erc-releven/.github#47]
current development preview: https://releven.acdh-dev.oeaw.ac.at
current production deployment: https://www.r11.eu

- [ ] include fonts
- header / footer
  - [x] fix layout
  - [x] remove login
  - [ ] finalize links/link texts
- pages
  - home page
    - [x] add tablet/phone layout
    - [x] figure out background behaviour on ultra-wide screens
    - [x] texts
  - about / faq
    - [x] get texts
- content pages
    - [x] implement query wrapper
    - [x] implement snappy caching
    - [x] implement ordering (depends on acdh-oeaw/rdfproxy#271)
    - [ ] implement filtering
    - people
      - [x] [implement rdfproxy endpoint](https://github.com/acdh-oeaw/wisski2rdfproxy/issues/1)
    - places
      - [ ] implement rdfproxy endpoint
    - texts
      - [x] implement rdfproxy endpoint
    - viewpoints
      - [ ] implement rdfproxy endpoint (based on acdh-oeaw/wisskas#20)
      - [ ] implement UI

**Comment by laletuver1** [comment]
The issue #49 needs to be fixed first before continuing.

**Comment by kevinstadler** [comment]
Running listing/detail endpoints allow further work on content pages -- before moving on: should locale support (i.e. `/en/` `/de/` as first part of the page URLs in https://releven.acdh-dev.oeaw.ac.at/en/search) be removed for good?

**Comment by tla** [comment]
Along the way of editing the text for the website main page, I have filled in what 'services' we should actually offer - basically network analysis and geographic visualization based on the data we (will) have collected. We should mark off the services as 'coming soon' for the September launch, and maybe change the hourglass and candle icons to be more appropriate for networks and maps.
